### ISSUE TITLE
Is it working? 

### ISSUE THREAD

**Issue by copercini** [davidmpye/EDB_FS#1]
Does it have an example of use?

**Comment by davidmpye** [comment]
Hi, yes, it works :-)

I have a project using it here:

https://github.com/davidmpye/RFID_access_controller/blob/master/code/lib/DBHandler/DBHandler.h

The interface is very similar to that of the original JWhiddon EDB

https://github.com/jwhiddon/EDB

Have a look at the EDB_FS header file  - Alas I haven't had the time to write a separate standalone example.  But it is MUCH faster on SPIFFS than EDB.

David
